version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      MONGO_URL: mongodb://localhost:27017/Easy-Chat
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
